INSERT INTO card (id,dtype,name, description, image, rarity, cost, public_id, health, strength) VALUES
                                                                                           (1,'Card','Fireball', 'A powerful fire spell.', NULL, 'Rare', 5, gen_random_uuid(), 3, 8),
                                                                                           (2,'Card','Ice Shard', 'Freezes enemies on hit.', NULL, 'Common', 2, gen_random_uuid(), 1, 3),
                                                                                           (3,'Card','Thunder Strike', 'A bolt of lightning.', NULL, 'Uncommon', 4, gen_random_uuid(), 2, 6),
                                                                                           (4,'Card','Healing Light', 'Restores health.', NULL, 'Rare', 3, gen_random_uuid(), 5, 1),
                                                                                           (5,'Card','Shield Wall', 'Increases defense temporarily.', NULL, 'Common', 1, gen_random_uuid(), 6, 0),
                                                                                           (6,'Card','Vampire Bite', 'Siphons health from opponent.', NULL, 'Rare', 4, gen_random_uuid(), 2, 5),
                                                                                           (7,'Card','Dragon’s Breath', 'Unleashes dragon fire.', NULL, 'Epic', 7, gen_random_uuid(), 10, 10),
                                                                                           (8,'Card','Swift Strike', 'A quick, low damage attack.', NULL, 'Common', 1, gen_random_uuid(), 1, 2),
                                                                                           (9,'Card','Meteor Shower', 'Summons meteors from the sky.', NULL, 'Legendary', 10, gen_random_uuid(), 8, 12),
                                                                                           (10,'Card','Poison Dart', 'Poisons the target.', NULL, 'Uncommon', 3, gen_random_uuid(), 2, 4),
                                                                                           (11,'Card','Iron Fist', 'A basic melee attack.', NULL, 'Common', 1, gen_random_uuid(), 3, 3),
                                                                                           (12,'Card','Mind Control', 'Takes control of an enemy.', NULL, 'Epic', 8, gen_random_uuid(), 1, 0),
                                                                                           (13,'Card','Earthquake', 'Shakes the ground.', NULL, 'Rare', 6, gen_random_uuid(), 6, 6),
                                                                                           (14,'Card','Arcane Blast', 'An explosive magic attack.', NULL, 'Uncommon', 4, gen_random_uuid(), 2, 7),
                                                                                           (15,'Card','Holy Shield', 'Protects from damage.', NULL, 'Epic', 7, gen_random_uuid(), 9, 1),
                                                                                           (16,'Card','Shadow Step', 'Dodges an attack.', NULL, 'Rare', 2, gen_random_uuid(), 0, 5),
                                                                                           (17,'Card','Healing Potion', 'Restores minor health.', NULL, 'Common', 1, gen_random_uuid(), 4, 0),
                                                                                           (18,'Card','Cursed Sword', 'Deals high damage, lowers health.', NULL, 'Uncommon', 5, gen_random_uuid(), 1, 9),
                                                                                           (19,'Card','Phoenix Feather', 'Revives on death.', NULL, 'Legendary', 10, gen_random_uuid(), 10, 0),
                                                                                           (20,'Card','Mana Drain', 'Drains enemy mana.', NULL, 'Rare', 3, gen_random_uuid(), 1, 4),
                                                                                           (21,'Card','Fire Shield', 'Burns attackers.', NULL, 'Uncommon', 4, gen_random_uuid(), 5, 3),
                                                                                           (22,'Card','Frost Nova', 'Freezes area around you.', NULL, 'Rare', 5, gen_random_uuid(), 4, 6),
                                                                                           (23,'Card','Lightning Bolt', 'Instant, high-damage strike.', NULL, 'Epic', 8, gen_random_uuid(), 3, 10),
                                                                                           (24,'Card','Invisibility Cloak', 'Becomes invisible.', NULL, 'Rare', 2, gen_random_uuid(), 0, 0),
                                                                                           (25,'Card','Time Stop', 'Pauses enemy movement.', NULL, 'Legendary', 9, gen_random_uuid(), 5, 1),
                                                                                           (26,'Card','Energy Burst', 'Releases stored energy.', NULL, 'Uncommon', 3, gen_random_uuid(), 2, 8),
                                                                                           (27,'Card','Magic Missile', 'Standard ranged spell.', NULL, 'Common', 2, gen_random_uuid(), 1, 4),
                                                                                           (28,'Card','Summon Golem', 'Brings forth a rock golem.', NULL, 'Epic', 6, gen_random_uuid(), 7, 7),
                                                                                           (29,'Card','Poison Cloud', 'Area poison attack.', NULL, 'Uncommon', 4, gen_random_uuid(), 4, 3),
                                                                                           (30,'Card','Divine Smite', 'Infused with holy power.', NULL, 'Legendary', 9, gen_random_uuid(), 7, 9);
