DROP TABLE IF EXISTS public.card_ability CASCADE;
DROP TABLE IF EXISTS public.deck_cards CASCADE;
DROP TABLE IF EXISTS public.player CASCADE;
DROP TABLE IF EXISTS public.card CASCADE;
DROP TABLE IF EXISTS public.deck CASCADE;

